//X X档案 数据接入分析数据data
export default {
  id: null,
  rootId: null,
  name: "X X市",
  url: null,
  type: null,
  pId: null,
  sort: null,
  code: null,
  children: [
    {
      id: null,
      rootId: null,
      name: "法院系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "司法系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "发改系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "编办系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "科技系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "民政系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "财政系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "人社系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "自然资源和规划系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "城建系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "住保系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "园林系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "交通系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "卫生健康系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "统计系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "生态环境系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "物价系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "公积金系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "税务系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "城管系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "农委系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "工信系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "公安系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "水务系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "商务系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "人防系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "审计系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "林业系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "粮食系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "文物系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "民委系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "爱卫系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "知识产权系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "宣传系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "电信系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "社保系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "退役军人事务系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "大数据管理系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "文化和旅游系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "公交系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "检察系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "国资系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "森林公安系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "红十字会系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "市场监管系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "应急管理系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "妇联系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "邮政系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "市场发展系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "团市委系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    },
    {
      id: null,
      rootId: null,
      name: "物流口岸系统",
      url: null,
      type: null,
      pId: null,
      sort: null,
      code: null,
      children: null,
      extend: null,
      icon: null,
      checked: null,
      nocheck: null,
      open: false,
      isParent: null,
      informationType: null
    }
  ],
  extend: null,
  icon: null,
  checked: null,
  nocheck: null,
  open: false,
  isParent: null,
  informationType: null
};
